---
title: "nyc-shiny-app-demo"
author: "Lillian Clark"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(tidyverse)
library(shinythemes)
library(sf)
library(ggplot2)
library(cowplot)
```

```{r}
inpatients_ny <- read.csv("data/ny_specific/medicare_inpatients_ny.csv")
medicare_ny <- read_csv("data/ny_specific/medicare_ny.csv")
ny_metro_map <- st_read("nyc_maps/ny_metro_map/ny_metro_map.shp", stringsAsFactors = FALSE)
ny_borough_map <- st_read("nyc_maps/ny_borough_map/ny_borough_map.shp", stringsAsFactors = FALSE)
medicare_by_county <- read_csv("data/ny_specific/medicare_by_county.csv")
```

```{r}
theme_custom <- function() {
    theme_light() +
        theme(plot.title = element_text(color = "white", size = 20, face = "bold", hjust = .5),
              plot.subtitle = element_text(color = "white", size = 14, hjust = .5),
              axis.title.x = element_text(color = "white", size = 14, face = "bold"),
              axis.title.y = element_text(color = "white", size = 13),
              axis.text.x = element_text(color = "white", size = 12),
              axis.text.y = element_text(color = "white"),
              axis.ticks = element_blank(),
              legend.title = element_text(color = "white", size = 10, face = "bold"),
              panel.background = element_rect(fill = "#292929", color = "#292929"),
              panel.border=element_blank(),
              panel.grid.minor=element_blank(),
              plot.background=element_rect(fill = "#292929", color = "#292929"),
              legend.background = element_rect(fill="#292929", size=0.5, linetype="solid"),
              legend.text = element_text(color = "white"))
}
```

```{r}
cols <- c("Below the national average" = "red", "Above the national average" = "#0A97F0", "Same as the national average" = "#B8DAEF")
```

```{r}
medicare_selected_rating <- medicare_ny
```

```{r}
medicare_selected_rating %>%
  ggplot(aes(x = effectiveness_of_care_national_comparison, 
                                 fill = effectiveness_of_care_national_comparison)) +
    scale_fill_manual(values = cols, na.value = "#7B7C7C") +
  geom_bar() +
  scale_x_discrete(labels=c("Above the national average" = "Above", "Below the national average" = "Below",
                                "Same as the national average" = "Same")) +
  labs(x = paste0(str_to_title(str_replace_all(str_remove("effectiveness_of_care_national_comparison", 
                                                          "_national_comparison"), "_", " ")), 
                                                          " Compared to the National Average"),
           y = "Number of Medicare hospital providers",
           title = paste0(str_to_title(str_replace_all(str_remove("effectiveness_of_care_national_comparison", 
                                                          "_national_comparison"), "_", " ")), 
                                                          " in NYC Metro Area"))+
  theme_custom() +
  theme(legend.position = "none")
```

```{r}
medicare_selected_rating <- medicare_ny %>%
  filter(!is.na(long), !is.na(lat))
```

```{r}
medicare_selected_rating %>%
  ggplot() +
  geom_sf(data = ny_metro_map, aes(geometry = geometry),
                   color="#E6E7E7", fill = "#F5F6F6") +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Same as the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .8) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Above the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .7) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Below the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .7) +
  geom_point(data = subset(medicare_selected_rating, 
                           is.na(effectiveness_of_care_national_comparison)),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .7) +
  scale_color_manual(values = cols, na.value = "#7B7C7C") +
  coord_sf() +
  theme_void() +
  theme(plot.caption = element_text(hjust = .5)) +
  labs(title = "Effectiveness of Care for Medicare Providers",
       color = "Effectiveness of care")
```

```{r}
medicare_selected_rating <- medicare_selected_rating %>%  
  filter(county %in% c("Bronx", "New York", "Queens", "Kings", "Richmond"))

medicare_selected_rating %>%
  ggplot() +
  geom_sf(data = ny_borough_map, aes(geometry = geometry),
                   color="#9EA5A9", fill = "#CED5DA") +
  geom_point(data = subset(medicare_selected_rating, 
                           is.na(effectiveness_of_care_national_comparison)),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .6) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Same as the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .4) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Above the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .4) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Below the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .4) +
  scale_color_manual(values = cols, na.value = "white") +
  coord_sf() +
  theme_void() +
  theme(plot.caption = element_text(hjust = .5)) +
  labs(title = "Effectiveness of Care for Medicare Providers",
       color = "Effectiveness of care")
```

```{r}
plot_sq <- function(factor){
    if (subset(medicare_by_county, county == "Bronx")[[factor]] == "Below the national average") {
      sqcolor <- "red"
    } else if (subset(medicare_by_county, county == "Bronx")[[factor]] == "Above the national average") {
      sqcolor <- "#0A97F0"
    } else if (subset(medicare_by_county, county == "Bronx")[[factor]] == "Same as the national average") {
      sqcolor <- "#B8DAEF"
    } else if (is.na(subset(medicare_by_county, county == "Bronx")[[factor]])) {
      sqcolor <- "#7B7C7C"
    }
  
  sq <- ggplot() +
  labs(tag = str_to_title(str_replace_all(factor, "_", " "))) +
  theme_custom() +
  theme(
    plot.tag.position = c(0.5, 0.5),
    plot.tag = element_text(color = "white", size = 40, face = "bold"),
    plot.background = element_blank(),
    panel.background = element_rect(fill = sqcolor, color = "white")
  )
  
  return (sq)
}
```

```{r}
lapply(c("effectiveness_of_care", "timeliness_of_care", "safety_of_care", "patient_experience", "readmission", "mortality"), plot_sq)
```
  
```{r}
ratings <- medicare_selected_rating %>%
  ggplot(aes(x = effectiveness_of_care_national_comparison, 
                                 fill = effectiveness_of_care_national_comparison)) +
    scale_fill_manual(values = cols, na.value = "#7B7C7C") +
  geom_bar() +
  theme_custom() +
  theme(legend.title = element_blank())

legend <- get_legend(ratings)
ggdraw(legend)
```

```{r}
library(broom)
```

```{r}
model_data <- medicare_by_county %>%
  select(timeliness_score:hospital_overall_rating)
```

```{r}
null_model <- lm(hospital_overall_rating ~ 1, data = model_data)
full_model <- lm(hospital_overall_rating ~ ., data = model_data)
```

```{r}
# Backward selection using AIC
regfit_backward <- step(full_model, direction = "backward")
```

```{r}
glance(regfit_backward)
regfit_backward$coefficients
```

```{r}
model_data3 <- medicare_ny %>%
  select(owner:timeliness_of_care_national_comparison)
```

```{r}
null_model <- lm(hospital_overall_rating ~ 1, data = model_data3)
full_model <- lm(hospital_overall_rating ~ ., data = model_data3)
```

```{r}
# Backward selection using AIC
regfit_backward <- step(full_model, direction = "backward")
```

```{r}
glance(regfit_backward)
regfit_backward$coefficients
```

```{r}
model_data2 <- medicare_by_county %>%
  select(hospital_overall_rating, pop_estimate_2018, pctpovall_2018, unemployment_rate_2017, median_household_income_2018)
```

```{r}
null_model <- lm(hospital_overall_rating ~ 1, data = model_data2)
full_model <- lm(hospital_overall_rating ~ ., data = model_data2)
```

```{r}
# Backward selection using AIC
regfit_backward <- step(full_model, direction = "backward")
```

```{r}
glance(regfit_backward)
regfit_backward$coefficients
```

```{r}
model_data2 <- medicare_by_county %>%
  select(hospital_overall_rating, pop_estimate_2018, pctpovall_2018, unemployment_rate_2017, median_household_income_2018)
```

```{r}
null_model <- lm(hospital_overall_rating ~ 1, data = model_data2)
full_model <- lm(hospital_overall_rating ~ ., data = model_data2)
```

```{r}
# Backward selection using AIC
regfit_backward <- step(full_model, direction = "backward")
```

```{r}
glance(regfit_backward)
regfit_backward$coefficients
```

```{r}
ny_metro_map <- ny_metro_map %>%
  rename(county = NAME)
ny_borough_map <- ny_borough_map %>%
  rename(county = NAME)

ny_borough_map <- ny_borough_map %>%
  mutate(county = case_when(
    county == "Brooklyn" ~ "Kings",
    county == "Staten Island" ~ "Richmond",
    county == "Manhattan" ~ "New York",
    TRUE ~ county))
```

```{r}
datamap <- right_join(medicare_by_county, ny_borough_map, by = "county")
```

```{r}
medicare_selected_rating <- medicare_selected_rating %>%  
  filter(county %in% c("Bronx", "New York", "Queens", "Kings", "Richmond"))

ggplot() +
  geom_sf(data = datamap, aes(geometry = geometry, fill = pctpovall_2018), color="white") +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Same as the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .8, size = 4) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Above the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .7, size = 4) +
  geom_point(data = subset(medicare_selected_rating, 
                           effectiveness_of_care_national_comparison == "Below the national average"),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .7, size = 4) +
  geom_point(data = subset(medicare_selected_rating, 
                           is.na(effectiveness_of_care_national_comparison)),
             aes(x = long, y = lat, color = effectiveness_of_care_national_comparison), 
             alpha = .7, size = 4) +
  scale_color_manual(values = cols, na.value = "#7B7C7C") +
  scale_fill_gradient(low = "#FCF3DD", high = "#FCB60B") +
  coord_sf() +
  theme_custom() +
  theme(plot.caption = element_text(hjust = .5),
        plot.title = element_text(size = 16),
        axis.line=element_blank(),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks=element_blank(),
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            panel.border=element_blank(),
            panel.grid.major=element_blank(),
            panel.grid.minor=element_blank()) +
  labs(title = "Effectiveness of Care for Medicare Providers",
       subtitle = "in New York City",
       color = "Effectiveness of care", 
       fill = "Percent in Poverty (2018)",
       caption = "Hospitals without ratings available shown in grey")
```

```{r}
ggplot(datamap, aes(x = county, y = effectiveness_score)) +
  geom_bar(stat = "identity")
```
